apiVersion: v2
name: todo-app
description: A Helm chart for Todo App deployment on Azure Kubernetes Service
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - todo
  - fastapi
  - kubernetes
home: https://github.com/yourusername/todo-app
sources:
  - https://github.com/yourusername/todo-app
maintainers:
  - name: Your Team
deprecated: false

